[GENERAL]
dt = 3600
max_layers = 50
z = 2.0

[PARAMETERIZATIONS]
stability_correction = "MO"
albedo_method = "Oerlemans98" #"Bougamont05"
densification_method = "Boone"
penetrating_method = "Bintanja95"
roughness_method = "Moelg12"
saturation_water_vapour_method = "Sonntag90"
thermal_conductivity_method = "bulk" #Sturm97, Calonne19
sfc_temperature_method = "Newton"

[INITIAL_CONDITIONS]
initial_snowheight_constant = 0.689387 #from COSMO SND
initial_snow_layer_heights = 0.1
initial_glacier_height = 191.366
initial_glacier_layer_heights = 0.5
initial_top_density_snowpack = 300.0
initial_bottom_density_snowpack = 600.0
temperature_bottom = 270.16
const_init_temp = 0.1
zlt1 = 0.06
zlt2 = 0.1

[PRECIPITATION]
center_snow_transfer_function = 1.0
spread_snow_transfer_function = 1
mult_factor_RRR = 1.0
minimum_snow_layer_height = 0.001
minimum_snowfall = 0.001

[REMESHING]
remesh_method = "log_profile"
first_layer_height = 0.01
layer_stretching = 1.2
merge_max = 1
density_threshold_merging = 5
temperature_threshold_merging = 0.01

[CONSTANTS]
constant_density = 300.0
albedo_fresh_snow = 0.85
albedo_firn = 0.55
albedo_ice = 0.3
albedo_mod_snow_aging = 6
albedo_mod_snow_depth = 8
t_star_wet = 10
t_star_dry = 30
t_star_K = 14
t_star_cutoff = 263.17
roughness_fresh_snow = 0.24
roughness_ice = 1.7
roughness_firn = 4.0 #4.0 #max 7
aging_factor_roughness = 0.0026
snow_ice_threshold = 900.0
lat_heat_melting = 334000.0
lat_heat_vaporize = 2500000.0
lat_heat_sublimation = 2834000.0
spec_heat_air = 1004.67
spec_heat_ice = 2050.0
spec_heat_water = 4217.0
k_i = 2.22
k_w = 0.55
k_a = 0.024
water_density = 1000.0
ice_density = 917.0
air_density = 1.1
sigma = 5.67e-8
zero_temperature = 273.16
surface_emission_coeff = 0.99
