# This is the utilities configuration file.
# Please make your changes here.
#
# To call variables in a utility script:
# from cosipy.utilities.config import UtilitiesConfig
# in_K = UtilitiesConfig.aws2cosipy.names["in_K"]
#
# Alternatively:
# cfg_names = UtilitiesConfig.aws2cosipy.names
# in_K = cfg_names["in_K"]

# AWS2COSIPY
[aws2cosipy.names]
PRES_var = 'PRES'
T2_var = 'T2'
in_K = true
RH2_var = 'RH2'
G_var = 'G'
RRR_var = 'RRR'
U2_var = 'U2'
LWin_var = 'LWin'
SNOWFALL_var = 'SNOWFALL'
N_var = 'N'

[aws2cosipy.coords]
WRF = false
aggregate = false
aggregation_step = 'H'
ELEV_model = true
delimiter = ','

[aws2cosipy.radiation]
radiationModule = 'Horayzon2022' #Moelg2009, Wohlfahrt2016, none
LUT = false
LUT_path = "./data/static/LUT_Rad.nc"
dtstep = 10800
tcart = 4.24
timezone_lon = 15.0
zeni_thld = 89.0

[aws2cosipy.points]
point_model = false
plon = 90.64
plat = 30.47
hgt = 5665.0

[aws2cosipy.station]
stationName = 'HEF'
stationAlt = 3030.0283
stationLat = 46.797478

[aws2cosipy.lapse]
lapse_T = -0.0065 # Temp K per m
lapse_RH = 0.0 # RH % per m (0 to 1)
lapse_RRR = 0.0 # mm per m
lapse_SNOWFALL = 0.0000 # Snowfall % per m (0 to 1)

[create_static.paths]
static_folder = "./data/static/"
dem_path = ""
shape_path = ""
output_file = ""

[create_static.coords]
tile = true
aggregate = true
aggregate_degree = 0.0
longitude_upper_left = 0.0
latitude_upper_left = 0.0
longitude_lower_right = 0.0
latitude_lower_right = 0.0

[wrf2cosipy.constants]
hu = 10
lu_class = 24
